CREATE USER db_user WITH PASSWORD 'db_pass';
CREATE DATABASE db_db;
CREATE DATABASE db_db_test;
GRANT ALL PRIVILEGES ON DATABASE db_db TO db_user;
GRANT ALL PRIVILEGES ON DATABASE db_db_test TO db_user;